-- Add new fields to customers table
ALTER TABLE customers
ADD COLUMN address_line1 VARCHAR(255) AFTER company_name,
ADD COLUMN address_line2 VARCHAR(255) AFTER address_line1,
ADD COLUMN city VARCHAR(100) AFTER address_line2,
ADD COLUMN pin_code VARCHAR(10) AFTER state_code,
ADD COLUMN mobile_no VARCHAR(15) AFTER contact_person,
ADD COLUMN telephone_no VARCHAR(15) AFTER mobile_no,
ADD COLUMN longitude DECIMAL(10, 8) AFTER email,
ADD COLUMN latitude DECIMAL(10, 8) AFTER longitude,
ADD COLUMN gst_registration_no VARCHAR(20) AFTER latitude,
ADD COLUMN pan_no VARCHAR(10) AFTER gst_registration_no,
ADD COLUMN freight_terms VARCHAR(50) DEFAULT 'FREIGHT INCL',
ADD COLUMN hsn_sac_code VARCHAR(20),
ADD COLUMN establishment_year INT,
ADD COLUMN turnover_year DECIMAL(15, 2),
ADD COLUMN payment_terms VARCHAR(50) DEFAULT '100% Advance',
ADD COLUMN security_cheque BOOLEAN DEFAULT FALSE,
ADD COLUMN credit_limit DECIMAL(15, 2) DEFAULT 0,
ADD COLUMN enterprise_type VARCHAR(50),
ADD COLUMN equity_type VARCHAR(50),
ADD COLUMN product_segment VARCHAR(50),
ADD COLUMN coordinator_name VARCHAR(100),
ADD COLUMN remarks TEXT,
ADD COLUMN customer_code VARCHAR(20) AFTER id;
